### PR TITLE
Drop PHP v7.3 support and upgrade CS Fixer to v3

### PR DESCRIPTION
**Pull request by mvorisek**
to support using `WeakReference` and other new features like `fn`, typed properties

### CODE REVIEW

**Comment by mvorisek** [comment]
@DarkSide666 @georgehristov ok to drop php 7.3 for upcoming 2.4 release?

we can already make ˙8.0˙ the latest CI image and develop for php 7.4 and 8.0 versions only.

**Comment by DarkSide666** [comment]
What advantage we get to deprecate 7.3 at this point?
I still use 7.3 quite a lot :)

**Comment by mvorisek** [comment]
Mostly syntactic sugar like short closures, with php 8 static return type, ... I do not pursue this PR fow now.

Someday we might transpile code for lower php versions.

**Comment by PhilippGrashoff** [comment]
Well, since 06.12.2020 there are only bugfixes, PHP 7.3:
https://www.php.net/supported-versions.php

At some point I think we decided to support PHP versions until they run out at php.net, so another year for PHP 7.3.

**Comment by PhilippGrashoff** [comment]
Do I really remember correctly? We dropped PHP 7.2 before it ran out. However, dropping version support too soon will probably piss off users.

**Comment by mvorisek** [comment]
I do not use PHP 7.3 anywhere, I support to drop PHP 7.3 immediatelly, let me know if we should merge :)

**Comment by DarkSide666** [comment]
I think we should support 7.3 until it runs out completely in php.net.
Exception could be in case 7.3 somehow really limits us to continue work on quality toolkit, but if that's just few changes in syntax between 7.3 and 7.4 and no really impressive and useful change, then I see no point to drop support earlier than php.net does that.

**Comment by mvorisek** [comment]
PHP 7.3 is already phased out from active development, let's remove the support for the upcoming atk4/* v3.0

**Comment by PhilippGrashoff** [comment]
Agreeing on this, lets drop it for upcoming versions. This also means that we can use typed properties where possible.

**Comment by mvorisek** [comment]
@PhilippGrashoff good point on typed props 👍

**Comment by PhilippGrashoff** [comment]
looking very good at first glance, thx for the work!

**Review by georgehristov — APPROVED** [review]

**Pull request merged**
