### PR TITLE
Shorten exception trace

### PR DESCRIPTION
**Pull request by mvorisek**
Before:
image

image

After:
image

image

Example code:
```
    try {
        throw new \atk4\ui\Exception('source');
    } catch (\atk4\ui\Exception $ex) {
        throw new \Exception('parent', 0, $ex);
    }
```

### CODE REVIEW

**Comment by romaninsh** [comment]
pls look into https://codeclimate.com/github/atk4/core/pull/152 too, if anything can be done there, not a problem either way]!

**Comment by abbadon1334** [comment]
> pls look into https://codeclimate.com/github/atk4/core/pull/152 too, if anything can be done there, not a problem either way]!

I see duplication can be avoided but i think that added complexity and the other one on conditional can be changed and defined as variables but i like is more workaround than a solution to avoid triggering codeclimate logic.

¯\_(ツ)_/¯

**Comment by mvorisek** [comment]
Yes, I will fix the large if and leave the duplicated code. It is not from ;-) - the exception renderers should actually be merged into one class as currently there is no way to extend them (or it needs to be done for every of them).

**Comment by mvorisek** [comment]
Even this was too huge for codeclimate - https://github.com/atk4/core/commit/7b8fa1b44ce05893ec22ad49e91b41930c1826fa ... Of course, it can be solved for ex. with foreach, but that will be not better that the current code.

**Pull request merged**
