### PR TITLE
Add PHPStan to CI

### PR DESCRIPTION
**Pull request by mvorisek**
exclude rules for traits generated by:
```
foreach (scandir(__DIR__) as $fname) {
    if (!preg_match('~.*Trait\.php$~', $fname)) {
        continue;
    }

    $d = file_get_contents($fname);
    preg_match_all('~(?:private|protected|public)[^\n()]+(?:function[^\n()]+?(\w+)\(|\$(\w+))~', $d, $matchesAll, \PREG_SET_ORDER);
    $methods = [];
    $props = [];
    foreach ($matchesAll as $matches) {
        //print_r($matches);
        if ($matches[1] !== '') {
            $methods[] = $matches[1];
        } else {
            $props[] = $matches[2];
        }
    }

    echo '        # for ' . $fname . "\n";
    foreach ($methods as $n) {
        echo '        - \'~^Call to an undefined method .+::' . preg_quote($n, '~') . '\(\)\.$~\'' . "\n";
    }
    foreach ($props as $n) {
        echo '        - \'~^Access to an undefined property .+::\$' . preg_quote($n, '~') . '\.$~\'' . "\n";
    }
}
```

### CODE REVIEW

**Comment by mvorisek** [comment]
for
```
 ------ ------------------------------------------------------------------------------ 
  Line   src/CollectionTrait.php (in context of class atk4\core\tests\CollectionMock)  
 ------ ------------------------------------------------------------------------------ 
  51     Call to an undefined method                                                   
         $this(atk4\core\tests\CollectionMock)::getApp().   
```

and simillar errors I think we need interfaces to check traits (or customize phpstan)

@georgehristov wdyt?

**Comment by georgehristov** [comment]
As we are on php 7.3 already we can use traits within traits already. php 7.2 had issues if these duplicate.
So in this case in CollectionTrait we can add `use AppScopeTrait`

**Comment by mvorisek** [comment]
> 
> 
> As we are on php 7.3 already we can use traits within traits already. php 7.2 had issues if these duplicate.
> So in this case in CollectionTrait we can add `use AppScopeTrait`

`in this case` :)

we of course needs to be able to support
```
if (something understandable by phpstan, language provides one way - interfaces, like $x instanceof AppScopeTraitInterface) {
    $x->getApp(); // phpstan must be sure $x has AppScopeTrait
}
```

**Comment by georgehristov** [comment]
Interfaces is the most correct way, agree

**Review by DarkSide666 — APPROVED** [review]
LGTM

**Pull request merged**
