### PR TITLE
Fix Markdown links in reStructured Text

### PR DESCRIPTION
**Pull request by szepeviktor**
Currently broken: https://agile-core.readthedocs.io/en/develop/
Preview: https://github.com/szepeviktor/atk4_core/blob/patch-1/docs/index.rst

Docs: https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#links-to-external-web-pages

### CODE REVIEW

**Comment by szepeviktor** [comment]
@mvorisek Oh nooo!! There are a lot more Markdown links in .rst file.

**Comment by mvorisek** [comment]
I personally prefer inlined links as there are easier to maintain.

ref: https://www.odoo.com/documentation/16.0/contributing/documentation/rst_cheat_sheet.html#external-hyperlinks
tested in https://www.tutorialspoint.com/online_restructure_editor.php

Also what is your opinion or rst vs. MD, what about converting everything from rst to MD?

**Comment by szepeviktor** [comment]
This is the first rst file I send a PR to :)

**Comment by mvorisek** [comment]
https://docs.readthedocs.io/en/stable/guides/migrate-rest-myst.html

**Comment by szepeviktor** [comment]
Would you like me to convert all .rst files to .md?

**Comment by mvorisek** [comment]
Yes, PR is welcomed.

I did some research:
- https://stackoverflow.com/questions/45633709/how-to-convert-rst-files-to-md#45641303
- https://stackoverflow.com/questions/74653392/pandoc-converting-restructuredtext-to-markdown-fails-on-headings
- https://pypi.org/project/rst-to-myst/

and the conversion from rst to md can be non-lossless, so I would like to see some discussion about different options considered.

I tried `rst-to-myst` and `pandoc` convertors. `rst-to-myst` is by order of magnitude better, but still a lot of manual changes are needed...

lint: https://github.com/DavidAnson/markdownlint

**Comment by mvorisek** [comment]
I am closing this PR as the docs require much more care.

**Comment by mvorisek** [comment]
I tried `rst-to-myst` and `pandoc` convertors. `rst-to-myst` is by order of magnitude better.

The next step is to compare the Sphinx output from the md data - https://stackoverflow.com/questions/2471804/using-sphinx-with-markdown-instead-of-rest

Once there are no differences, I will push the changes.

https://myst-parser.readthedocs.io/en/latest/intro.html MyST options

https://github.com/DavidAnson/markdownlint linter for CI, especially EOL and wrapping, also test prettier

then the docs can be deployed onto GH pages

**Comment by mvorisek** [comment]
Fixed in:
- https://github.com/atk4/core/pull/383
- https://github.com/atk4/data/pull/1109
- https://github.com/atk4/ui/pull/2085

and

- https://github.com/atk4/core/pull/381
- https://github.com/atk4/data/pull/1107
- https://github.com/atk4/ui/pull/2080

a week of hard work, but MyST is the future, rst was syntax hell

**Comment by szepeviktor** [comment]
I wish you good work.

**Pull request closed without merging**
