### PR TITLE
Update codecov.yml

### PR DESCRIPTION
**Pull request by mvorisek**
Nomalize, remove comment and remove default config values.

DO NOT MERGE until the coverage drop test by deleted test https://github.com/atk4/core/pull/186/commits/fdab64b9d79bfe1c1bb2b24024735604aa44415d is reverted

And of course revert all tests except the config itself.

Default file: https://docs.codecov.io/docs/codecov-yaml#section-default-yaml

`range` is used only for heatmap coloring.

image

### CODE REVIEW

**Comment by romaninsh** [comment]
@mvorisek do you plan to re-add the unit test?

**Comment by mvorisek** [comment]
@romaninsh of course, this PR is solely about tuning Codecov to prevent comments / red light on no/small coverage change as agrred with @DarkSide666

**Review by georgehristov — APPROVED** [review]
LGTM

**Review by georgehristov — APPROVED** [review]
LGTM

**Review by georgehristov — APPROVED** [review]
LGTM

**Review by georgehristov — APPROVED** [review]

**Pull request merged**
