### PR TITLE
Implement session trait

### PR DESCRIPTION
**Pull request by DarkSide666**
Simple implementation of SessionTrait.

### CODE REVIEW

**Comment by romaninsh** [comment]
@DarkSide666 to answer your question - different frameworks implement session in various ways. The point of Agile Core / Data and DSQL is to work anywhere.

Because core functionality of DSQL / Data do not require use of sessions, we shouldn't even implement them. I'm merging the request, but it will be migrated into the ATK framework when it's ready.

**Comment by romaninsh** [comment]
Actually we should probably put warning about this, we don't want users to start rely on Session and then remove them. 

It's a head-scratcher ;)

**Comment by DarkSide666** [comment]
well, maybe you shouldn't merge sessions then and simply delete that branch?

**Comment by romaninsh** [comment]
I'll add warning into documentation.

**Comment by DarkSide666** [comment]
ok

**Pull request merged**
